[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "containerguard-server"
version = "1.0.0"
dependencies = [
    "fastapi",
    "sqlalchemy[asyncio]",
    "asyncpg",
    "alembic",
    "pydantic-settings",
    "gunicorn",
    "uvicorn",
    "prometheus_client"
]
readme = "readme.md"
